import './globals.css';
import type { Metadata } from 'next';
import { GlobalProvider } from '@/lib/context/GlobalContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function WebAppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GlobalProvider>
        <main className="p-4">
            {children}
        </main>
    </GlobalProvider>
  );
}
